# Data Structures + Control Flow


## List Basics
 * Literals
 * Elements
 * Indexing
 * Negative indices
 * Slicing
 * Overwriting
 * Length (`len`)
 * Concatenation

In [10]:
import math
random = ["cat", 5, 4, 6, print, math]
letters = ['a', 'b', 'c', 'd', 'e', 'f']
schmetters = letters

In [11]:
letters[3:5]

['d', 'e']

In [12]:
start = 1
stop = 4

print(letters[2:])
print(letters[-2:])

print(letters[start:stop])

['c', 'd', 'e', 'f']
['e', 'f']
['b', 'c', 'd']


In [13]:
letters[0] = 'alpha'


In [14]:
print(letters)
print(schmetters)

['alpha', 'b', 'c', 'd', 'e', 'f']
['alpha', 'b', 'c', 'd', 'e', 'f']


In [19]:
print(id(letters))
print(id(schmetters))

1617451212552
1617451212552


In [22]:
sweaters = letters.copy
print(sweaters)

<built-in method copy of list object at 0x00000178979ADF08>


In [24]:
print(id(letters))
print(id(schmetters))
print(id(sweaters))

1617451212552
1617451212552
1617428258152


In [25]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [29]:
print('abc' + 'def')
print((1,2,3) + (4,5,6))

abcdef
(1, 2, 3, 4, 5, 6)


In [41]:
import numpy as np

vec1 = np.array((1,2,3))

vec2 = np.array((4,5,6))

In [42]:
vec1

array([1, 2, 3])

In [43]:
vec2

array([4, 5, 6])

In [44]:
vec1 + vec2

array([5, 7, 9])

## List Methods
 * `sort`
 * `sorted`
 * `reverse`
 * `append`
 * `extend`
 * `pop() & pop(i)`
 * `insert(i)`
 * `del`
 * `.remove()`
 * Testing membership with `in`
 * Locating index with `.index(value)`

In [54]:
dir(sort)

NameError: name 'sort' is not defined

In [60]:
elems = [4,2,6,5,9,1]

In [61]:
type(elems)

list

In [62]:
print(elems)

[4, 2, 6, 5, 9, 1]


In [70]:
print(sort(elems))

NameError: name 'sort' is not defined

In [71]:
elems.sort()

In [72]:
elems

[1, 2, 4, 5, 6, 9]

In [73]:
elems.reverse()

In [74]:
elems

[9, 6, 5, 4, 2, 1]

In [75]:
elems.append('this is a new element')
print(elems)

[9, 6, 5, 4, 2, 1, 'this is a new element']


In [76]:
elems.sort

<function list.sort(*, key=None, reverse=False)>

In [81]:
elems.extend([4,5,6])

In [82]:
elems

[9, 6, 5, 4, 2, 1, 'this is a new element', 4, 5, 6]

In [84]:
jobs = ['job1', 'job2', 'job3', 'job4', 'job5']
print(jobs.pop())
print(jobs.pop())
print(jobs)

job5
job4
['job1', 'job2', 'job3']


In [85]:
del jobs[-1]
print(jobs)

['job1', 'job2']


In [87]:
jobs = ['job1', 'job2', 'job3', 'job4', 'job5']
print(jobs.pop(2))
print(jobs)

job3
['job1', 'job2', 'job4', 'job5']


In [88]:
jobs.insert(2, 'job3')

In [89]:
print(jobs)

['job1', 'job2', 'job3', 'job4', 'job5']


3
3


'de'

## Lists and Strings
 * Indexing in to strings
 * len(str)
 * Slicing strings
 * Concatenating strings vs lists
 * `split`, e.g. `"I'm not a businessman\nI'm a business, man.".split("\n")`
 * "DELIMITER".join(), e.g. `"\n".join(["This is the first line.", "This is the second line."])`

In [93]:
print(len(['a', 'b', 'c']))
print(len('abc'))

3
3


In [94]:
'abcdefg'[3:5]

'de'

In [97]:
tokens = "I am not a businessman \n I'm a business, man".split("\n")
print(tokens)

['I am not a businessman ', " I'm a business, man"]


In [98]:
"\n".join(tokens)

"I am not a businessman \n I'm a business, man"

## Mutability 
 * Copying lists
 * Copying vs assignments
 * Appending to a copy
 * Copying slices

## Loops
 * `for item in list:
 * `for i in range(n):`
            `range(start, stop):`
            `range(start, stop, increment):`
                               -n
 * Style: 4 tabs
 * Refs for style: PEP8 (https://www.python.org/dev/peps/pep-0008/)
 * Converting with `list(range)`
 * Slicing and testing membership
 * Looping on strings

In [100]:
names = ['Phillip', 'Caroline', 'Prianka', 'Sarah', "Steven"]

for name in names:
    print("Hello, " + name)

for i in range(10):
    print(i)

Hello, Phillip
Hello, Caroline
Hello, Prianka
Hello, Sarah
Hello, Steven
0
1
2
3
4
5
6
7
8
9


In [101]:
print(math)

<module 'math' (built-in)>


In [103]:
print(['a','b',3,5,math])

['a', 'b', 3, 5, <module 'math' (built-in)>]


In [114]:
class Cat:
    def __init__(self, name, age):
        self.name = name
        self.age
    def __str__(self):
        return self.name

In [115]:
cat1 = Cat("Felix", 26)

AttributeError: 'Cat' object has no attribute 'age'

In [116]:
print(cat1)

NameError: name 'cat1' is not defined

## Get out!
 * Continue 
 * Break

## Boolean Values and Operators
 * True, False
 * `and`, `or`, `not`
 * `xor` (== `!=`)
 * Testing equality with `==` and `!=`
 * Comparators: `>`, `<`, `>=`, `<=`
 * Membership tests via `in`
 * 0 == False.
 * 1 == True.
 * 1.1 == True?
 * Casting to Boolean `bool()`
   * 5 == True vs bool(5) == True 
 * Testing logical equivalence with `==` vs "same object" with `is`
   * `5 is 5`?, `[] is []`?

## Conditionals
 * If
 * If-Else
 * If-Elif-Else
 * One-liners:
    * `if <expr>: <statement>`
    * `if <expr>: <statement_1>; <statement_2>; ...; <statement_n>`
    * `<expr1> if <conditional_expr> else <expr2>`
 * Combination with assignment

## Keeping the Interpreter happy 
When a statement is required...

```if True:
    pass```

## Dictionaries:
 * Literals: `{'key': [value]}`
 * Access `my_dict['key']`
 * Insertion 
 * Looping with dictionaries
   * `for key, value in my_dict.items:`
   * `for key in my_dict.keys:`
   * `for value in my_dict.values:`
 * Testing membership
 * Deleting from dict w `del my_dict['key']`
 * Nesting lists and dictionaries
 * The `in` statement for dictionaries (test key membership)

## List comprehensions
 * Basic comprehension: `[expression(item) for item in collection]`
 * Filter comprehension: `[expression(item) for item in list if filter(i)]`
 * Comparison to verbose expression with for loop (for both basic and filtered).
 * Exercises:
   * Print all the squares
   * Print only the even squares

## Tuples
 * Immutable
 * Behaves like lists
 * Neither contents nor elements can be changes

In [85]:
x = ('a', 'b', 'c')
print(x[ 1])
# x[1] = 'd'  # <=== ERROR

b


## Advanced / Miscellany
 * Zipping up lists
 * Map
   * `map(fun_my_list`)
   * `map(lambda n: fn(n), my_list)
   * `list(map(fun, my_list))`
 * Sets `set([1,2,3,4,1,1,2])`
 * DefaultDict: `from collections import defaultdict`
    * my_dict = defaultdict(lambda: value)`
    * `defaultdict(int)` # Defaults to 0